"""empty message

Revision ID: 3670c81ede8c
Revises: 5e81b3e469af
Create Date: 2025-08-01 09:39:47.063760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3670c81ede8c'
down_revision = '5e81b3e469af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
