"""empty message

Revision ID: a38fdf92463a
Revises: 3670c81ede8c
Create Date: 2025-08-01 10:06:52.299874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38fdf92463a'
down_revision = '3670c81ede8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
